pp-spell-checker | Keenan Ng
dotkeenan/practice-problems pull request #17
Opened 2020-09-17 01:09 UTC by dotkeenan

![pp-spell-checker](https://user-images.githubusercontent.com/18623005/93407738-b1592f80-f847-11ea-97a3-e6498537b72e.png)

2020-09-17 22:09 UTC, codingcodymiller requested changes

2020-09-17 22:09 UTC, codingcodymiller commented on spell-checker/main.js
> +  spellingObject['correct'] = correctWords;
This shouldn't be the list of all correct words, it should be the list of words that were spelled correctly by the user 👍

2020-09-17 23:52 UTC, dotkeenan commented
![pp-spell-checker](https://user-images.githubusercontent.com/18623005/93539599-25f2a380-f906-11ea-8daa-3bc190ef9d10.png)

2020-09-18 00:34 UTC, codingcodymiller approved these changes

2020-09-18 00:35 UTC, merged